movieproject/movieapp/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views
app_name= 'movieapp'
urlpatterns = [

    path('', views.index,name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie,name='add_movie'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete')

 ]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movieapp.urls"))


]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    Name=models.CharField(max_length=250)
    Description=models.TextField()
    Year=models.IntegerField()
    Img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.Name

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from . models import Movie
from . form import MovieForm
# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={ 'movie_list':movie}
    return render(request,'index.html', context)

def detail(request, movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,'detail.html', {'movie':movie})

def add_movie(request):
    if request.method=="POST":
        Name=request.POST.get('Name')
        Description = request.POST.get('Description')
        Year = request.POST.get('Year')
        Img = request.FILES['Img']
        movie=Movie(Name=Name,Description=Description,Year=Year,Img=Img)
        movie.save()
        return redirect('/')
    return render(request, 'add.html')
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=="POST":
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="Name" placeholder="Enter Name">
    <input type="text" name="Description" placeholder="Enter the Description">
    <input type="text" name="Year" placeholder="Enter Year">
    <input type="file" name="Img">
           <input type="submit">

</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movies</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">

    Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
  Are you sure??
  <input type ='submit'>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class ="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.Img.url}}" width="400" height="500">
        </div>
        <div class="col-md-6">
            <h2>{{movie.Name}}</h2>
            <h5>{{movie.Description}}</h5>
            <h4>{{movie.Year}}</h4>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a><br>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a><br>
    </div>
</div>
{% endblock %}

movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type ='submit'>
</form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container" xmlns:background-color="http://www.w3.org/1999/xhtml">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card">
  <img src="{{i.Img.url}}" class="card-img-top" alt="..." width="600px" height="500px">
  <div class="card-body">
    <h5 class="card-title">{{i.Name}}</h5>
    <p class="card-text">{{i.Description}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">More</a>

  </div>
</div>
    </div>
        {% endfor %}
                           <div class="col-md-3">
<div class="text-center">
    <a href="{% url 'movieapp:add_movie' %}" class="btn btn-primary btn-lg" style="width: 300px; height: 500px; background-color: white; color: black; border: 1px solid black; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; font-size: 100px;">

        +
    </a>
</div>

</div>


{% endblock %}